USE scpfoundation_db;


INSERT INTO department (department_name, department_location)
VALUES ( "CONTAINMENT SECTOR 1", "ANTARTICA"),
       ( "CONTAINMENT SECTOR 2", "TIBET"),
       ("CONTAINMENT SECTOR 3", "BERMUDA"),
       ("CONTAINMENT SECTOR 4", "MOON"),
       ("CONTAINMENT SECTOR 5", "REDACTED"),
        ("RESEARCH & DEVELOPMENT" , "LONDON"),
        ("TRAINING - ADMINISTRATIVE", "LONDON"),
        ("TRAINING - COMBAT", "DALLAS"),
        ("F.E.A.R SQUADS", "REDACTED"),
        ("RECOVERY/ERASURE", "REDACTED"),
        ("PUBLIC RELATIONS", "NEW YORK"),
        ("ENGINEERING", "DALLAS"),
        ("INFO-WAR", "CALIFORNIA"),
        ("PSY-OP","NEW YORK"),
        ("ADMINISTRATION", "NEW YORK"),
        ("HUMAN RESOURCES - NA", "NEW YORK"),
        ("HUMAN RESOURCES - EU", "BERLIN"),
        ("HUMAN RESOURCES - ASIA", "HONG-KONG"),
        ("OCCULT REQUISITIONS", "BERLIN"),
        ("ARCHAEOLOGY", "EGYPT");


INSERT INTO roles (job_title, salaries)
VALUE   ("CEO",  100000000),
        ("Director",  750000),
        ("Containment-Specialist",  200000),
        ("Researcher",  200000),
        ("Trainer",  200000),
        ("F.E.A.R",  0 ),
        ("Investigator",  60000),
        ("PR-Specialist",  50000),
        ("Engineer",  200000),
        ("Netrunner",  0),
        ("Interrogator", 200000),
        ("Processor",  45000),
        ("Secretary",  45000),
        ("Intern",  0),
        ("Liason",  45000),
        ("Janitor",  45000),
        ("HR-Specialist",  45000),
        ("Retriever",  75000),
        ("Archaeologist",  75000);

INSERT INTO employees (first_name, last_name, role_id, manager,active_status)
VALUES ("John", "Smith", 01, true, "MIA"),
        ("La'isha","REDACTED", 02, true, "ACTIVE"),
        ("Crane", "REDACTED", 02, true, "ACTIVE"),
        ("Xin", "REDACTED" , 02, true, "MIA"),
        ("Danielle", "REDACTED", 02, true ,"ACTIVE"),
        ("Trinity", "REDACTED",  02, true ,"ACTIVE"),
        ("Cain", "Bazilvuel",  02, true ,"MIA"),
        ("Jane", "Carter",  02, true ,"ACTIVE"),
        ("Wilmur", 'Streisand',  02,  true, "ACTIVE"),
        ("Samuel", "Rain",  02,  true, "REDACTED"),
        ("Helena", "Strauss",  02,  true, "ACTIVE"),
        ("Jerome","Roberts",  02, true, "ACTIVE"),
        ("Appella", "REDACTED", 02, true, "ACTIVE"),
        ("Charles", "Chunchen",  02, true, "MIA"),
        ("Haley", "Shen",  02,  true ,"KIA"),
        ("Jerry", "Harper",  02, true ,"ACTIVE"),
        ("Sully", "Santos",  02, true ,"ACTIVE"),
        ("Tracey", "Carter",  02, true ,"ACTIVE"),
        ("Gerald", 'Streisand',  02, true, "ACTIVE"),
        ("Viktor", "Strauss",  02, true, "ACTIVE"),
        ("Indiana", "Jones",   02,  true, "MIA"),
        ("REDACTED","REDACTED", 03,  false, "ACTIVE"),
        ("Holdt","REDACTED", 03,false, "ACTIVE"),
        ("Eric","REDACTED",  03,false, "KIA"),
        ("Sherry","REDACTED", 03, false, "ACTIVE"),
        ("Mohammed","REDACTED", 03, false, "ACTIVE"),
        ("REDACTED","REDACTED", 03,  false, "ACTIVE"),
        ("REDACTED","REDACTED", 03,false, "ACTIVE"),
        ("Borje","REDACTED", 03, false, "ACTIVE"),
        ("Bozidar","REDACTED", 03, false, "ACTIVE"),
        ("Shannon","REDACTED", 03, false, "ACTIVE"),
        ("Bozidar","REDACTED", 03, false, "REDACTED"),
        ("Neophytos","REDACTED", 03,  false, "REDACTED"),
        ("Selena","REDACTED", 03,  false, "REDACTED"),
        ("Freyja","REDACTED", 03, false, "REDACTED"),
        ("Aviyah","REDACTED", 03,false, "REDACTED"),
        ("Julijana","REDACTED", 03,false, "REDACTED"),
        ("Vivis","REDACTED", 03, false, "ACTIVE"),
        ("Karin","REDACTED", 03, false, "KIA"),
        ("Priamos","REDACTED", 03,false, "KIA"),
        ("Juter","REDACTED", 03,false, "REDACTED"),
         ("Fito","REDACTED", 03,false, "ACTIVE"),
        ("Jitendra","REDACTED", 03, false, "REDACTED"),
        ("walery","REDACTED", 03, false, "REDACTED"),
        ("Abisai","REDACTED", 03, false, "REDACTED"),
        ("Marinela","REDACTED", 03, false, "REDACTED"),
        ("REDACTED","REDACTED", 03,false, "REDACTED"),
        ("REDACTED","REDACTED", 03, false, "REDACTED"),
        ("REDACTED","REDACTED", 03, false, "REDACTED"),
        ("REDACTED","REDACTED", 03, false, "REDACTED"),
        ("REDACTED","REDACTED", 03, false, "REDACTED"),
         ("REDACTED","REDACTED", 03, false, "REDACTED"),
        ("Roosje","Viss", 06, false, "ACTIVE"),
        ("Shel","Harper", 06,false, "ACTIVE"),
        ("Shiela","Smith", 06, false, "ACTIVE"),
        ("Cebrian","Lee", 06,false, "ACTIVE"),
         ("Jason","Ma", 06,false, "REDACTED"),
        ("Demetria","Belos", 07, false, "ACTIVE"),
        ("Ankit","Sumiri", 07,false, "ACTIVE"),
        ("Nicol","Lee", 08, false, "ACTIVE"),
        ("Kolya","REDACTED", 09 , false, "ACTIVE"),
        ("Trym","REDACTED", 09 ,false, "ACTIVE"),
        ("Costanzo","REDACTED", 09 ,false, "ACTIVE"),
        ("Lilith","REDACTED", 09 ,false, "MIA"),
        ("Bira","REDACTED", 09 ,false, "ACTIVE"),
        ("Valeri","REDACTED", 09 ,false, "ACTIVE"),
        ("Georgiy","REDACTED", 09 ,false, "KIA"),
        ("Mariann","REDACTED", 09 ,false, "KIA"),
         ("Artur","REDACTED", 09 ,false, "KIA"),
        ("Ian","REDACTED", 09 ,false, "ACTIVE"),
        ("Oleg","REDACTED", 09 ,false, "ACTIVE"),
        ("Aniruddah","REDACTED", 09 ,false, "ACTIVE"),
        ("Lanre","REDACTED", 09 , false, "ACTIVE"),
        ("Hurst","REDACTED", 09 , false, "ACTIVE"),
        ("Teresa","Ophe", 07 , false, "ACTIVE"),
        ("Mirko","Ophe", 07 , false, "ACTIVE"),
        ("Cher","Ishnikov", 07 , false, "ACTIVE"),
        ("Echo","REDACTED", 08 , false, "ACTIVE"),
        ("Gualberto","Roberts", 09 ,false, "ACTIVE"),
        ("Eir","Falger", 09 ,false, "ACTIVE"),
        ("Hitachi","Muramasa", 09,false, "ACTIVE"),
        ("Zeynaeb", "kalashkov", 09, false, "ACTIVE"),
        ("Florian",'Smith', 10,false, "Active"),
        ("REDACTED",'REDACTED', 10, false, "Active"),
        ("REDACTED",'REDACTED', 10, false, "Active"),
        ("Gary","Lucard", 10,false, "MIA"),
        ("Akhil",'Ishmael', 11, false, "Active"),
        ("Gille",'De Rais', 11,false, "Active"),
        ("Sabah","ud Din", 12, false, "ACTIVE"),
        ("Cathalan","Isha", 12, false, "ACTIVE"),
        ("Sabine","Smith", 12,false, "ACTIVE"),
        ("Kalus","Joran", 12,false, "ACTIVE"),
        ("Gleb","Wayne", 12, false, "ACTIVE"),
        ("Jude","Carter", 12,false, "ACTIVE"),
        ("Thando","Belle",  13,false, "ACTIVE"),
        ("John","Lang",  13,false, "ACTIVE"),
         ("Arthur","Ma",  14,false, "ACTIVE"),
        ("Jason","Yuri",  14,false, "ACTIVE"),
        ("Antoine","Payne",  15, false,"ACTIVE"),
        ("Sarah","REDACTED",  16, false,"ACTIVE"),
        ("Teag","REDACTED",  16, false,"REDACTED"),
        ("Potesha","REDACTED", 16, false, "ACTIVE"),
        ("Harry", "Cains", 17, false, "Active"),
        ("Christian", "Douge", 17, false, "Active"),
         ("Hjal", "Finneist", 17 , false,"Active"),
          ("Kesha", "Douglas", 18, false, "Active"),
           ("Nauk", "Voldenvair", 18, false, "Active"),
            ("Isolde", "Kains", 19,false, "Active"),
            ("Sanjay", "Leis",  19,false,"REDACTED"),
            ("Vulferam", "Eissen", 19,false,"REDACTED"),
            ("Gabriel", "Lucas", 19,false,"REDACTED"),
            ("Kristina", "Lucas", 19,false,"REDACTED");
